version: '3.8'

services:
  spring-app-blue:
    image: ${DOCKER_IMAGE}:${VERSION}
    ports:
      - "${BLUE_PORT}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      balearn-net:

  spring-app-green:
    image: ${DOCKER_IMAGE}:${VERSION}
    ports:
      - "${GREEN_PORT}:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      balearn-net:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring-app-blue
      - spring-app-green
    networks:
      balearn-net:

networks:
  balearn-net:
    driver: bridge