spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  datasource:
    url: jdbc:mysql://${DATABASE_IP}:3306/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: http://${elasticsearch.host}:${elasticsearch.port}  # Elasticsearch 서버 주소
    connection-timeout: 5s
    socket-timeout: 10s

redis:
  host: ${REDIS_HOST}
  port: 6379

logstash:
  host: balearn-logstash
  port: 5000

elasticsearch:
  host: ${ES_HOST}
  port: 9200

kibana:
  host: balearn-kibana
  port: 5601

frontend:
  url: http://localhost:3000


